|| Component || Type || Message |
| RefreshBatch | Info | Refreshing MV_OPERATOR |
| RefreshBatch | Error | Could not refresh MV_OPERATOR : org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.jboss.util.NestedSQLException: No ManagedConnections available within configured blocking timeout ( 30000 \[ms\] ); - nested throwable: (javax.resource.ResourceException: No ManagedConnections available within configured blocking timeout ( 30000 \[ms\] ))
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:427)
at com.bics.smspricing.batch.RefreshBatch.refresh(RefreshBatch.java:29)
at com.bics.smspricing.batch.RefreshBatch.execute(RefreshBatch.java:21)
at com.bics.smspricing.batch.AbstractBatch.run(AbstractBatch.java:34)
at com.bics.smspricing.batch.LinkedBatch.execute(LinkedBatch.java:23)
at com.bics.smspricing.batch.AbstractBatch.run(AbstractBatch.java:34)
at com.bics.smspricing.batch.LinkedBatch.execute(LinkedBatch.java:23)
at com.bics.smspricing.batch.AbstractBatch.run(AbstractBatch.java:34)
at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:264)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:86)
at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: org.jboss.util.NestedSQLException: No ManagedConnections available within configured blocking timeout ( 30000 \[ms\] ); - nested throwable: (javax.resource.ResourceException: No ManagedConnections available within configured blocking timeout ( 30000 \[ms\] ))
at org.jboss.resource.adapter.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:95)
at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
... 17 more |

